# Generated by Django 3.2 on 2022-10-07 22:01

import cancerDetect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('has_cancer', models.BooleanField(blank=True, null=True)),
                ('cancer_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CancerDetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=cancerDetect.models.user_directory_path)),
                ('patient_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
