# Generated by Django 3.2 on 2023-03-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancerDetect', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancerDetail',
        ),
        migrations.RemoveField(
            model_name='cancerdetect',
            name='patient_name',
        ),
    ]
